### ISSUE TITLE
Empty space

### ISSUE THREAD

**Issue by DealsBeam** [nagahitoyuki/imaginary-liquid#5]
Empty space with no gadgets https://i.imgur.com/H3fgPeI.png

**Comment by nagahitoyuki** [comment]
### How to not show the floating bar

If you don't want to show the floating bar, delete the following codes inside body tag from Edit HTML.

```
<main id='content_wrapper'>
↓
<div id='floating_bar'>
  <div id='floating_menu'>

（floating bar codes）

  </div>
</div>
↑
<b:if cond='data:view.isArchive or (data:view.isSearch and data:view.search.resultsMessageHtml)'>
```

They are from under `<main id='content_wrapper'>` to above `<b:if cond='data:view.isArchive or (data:view.isSearch and data:view.search.resultsMessageHtml)'>`.

There are other unnecessary codes, so you can delete them.

**CSS part (inside b:skin tag)**

```
/* Floating bar */
(floating bar codes)
```

**JavaScript part (inside script tag at the bottom of HTML)**

```
/* Hamburger menu */
(hamburger menu codes)

/* Close button */
(close button codes)

/* Feed button */
(feed button codes)

/* Share menu */
(share menu codes)
```

If you don't use any search widgets, you don't need the following codes.

**CSS part (inside b:skin tag)**

```
/* Search widget */
(search widget codes)
```

**JavaScript part (inside script tag at the bottom of HTML)**

```
/* Search button */
(search button codes)
```

### How to not show the sidebar

If you don't want to show the sidebar, set the sidebar width
and content margin ​​to 0 in theme designer

[Check here for details](https://github.com/nagahitoyuki/imaginary-grid/issues/2#issuecomment-966766927)
